version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  impresso-middle-layer:
    image: impresso/impresso-middle-layer
    environment: 
      NODE_ENV: docker
    depends_on:
      - redis
    ports:
      - 3030:3030
    volumes:
      - ../config/development-docker.json:/impresso-middle-layer/config/docker.json
